on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      Environement:
        default: 'All'
        type: choice
        options:
          - All

permissions:
  id-token: write
  contents: read

jobs:
  TF_Plan_DEV_Cluster:
    name: "TF_Plan_DEV_Cluster"
    if: ${{ (github.event_name == 'push' || inputs.Environement == 'All' || inputs.Environement == 'TF_Plan_DEV_Cluster') && (github.ref == 'refs/heads/master') }}
    uses: ./.github/workflows/TF_Plan.yml
    with:
      ENV: dev
    secrets: inherit  

  TF_Apply_DEV_Cluster:
    name: "TF_Apply_DEV_Cluster"
    needs: TF_Plan_DEV_Cluster
    if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && (github.ref == 'refs/heads/master') && ( needs.TF_Plan_DEV_Cluster.outputs.TFPlanExitCode == 2 ) }}
    uses: ./.github/workflows/TF_Apply.yml
    with:
      ENV: dev
    secrets: inherit  
