on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs: 
  Terraform_Plan:
    name: "Terraform_Apply"
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV }}
    outputs:
      tfplanExitCode: ${{ steps.plan.outputs.TFPlanExitCode }}    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::033614065377:role/TF_Github_Action
          role-session-name: samplerolesession
          aws-region: ${{ inputs.aws_region }}

      - name: Terraform init
        id: init
        run: terraform init -upgrade -backend-config=backend-${{ inputs.ENV }}.hcl

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.ENV }}-tfplan
          path: .

      - name: "Terraform Apply"
        id: apply
        run: |
          terraform apply -no-color -auto-approve -input=false ${{ inputs.WORK_DIRECTORY }}/tfplan